{"name": "test_login_all_users[performance_glitch_user]", "status": "failed", "statusDetails": {"message": "AssertionError: Operation took too long: 5.15 seconds (maximum allowed: 3 seconds)", "trace": "self = <test_login_all_users.TestLogin object at 0x104fecd60>, driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"b69231a9a52c6157528542f02105adac\")>, username = 'performance_glitch_user'\n\n    @pytest.mark.parametrize(\"username\", [\n        \"standard_user\",\n        \"locked_out_user\",\n        \"problem_user\",\n        \"performance_glitch_user\",\n        \"error_user\",\n        \"visual_user\"\n    ])\n    def test_login_all_users(self, driver, username):\n        driver.get(\"https://www.saucedemo.com\")\n    \n        login_page = Login(driver)\n        screenshot = Screenshot(driver)\n        timer = Timer()\n    \n        timer.start()\n        login_page.perform_login(username, \"secret_sauce\")\n        timer.stop()\n    \n        # Take screenshot before any assertions\n        screenshot.take_screenshot(f\"login_{username}\")\n    \n        # Now do assertions - if they fail, we already have the screenshot\n        inventory = driver.find_element(\"id\", \"inventory_container\")\n        assert inventory.is_displayed(), f\"Login failed for user: {username}\"\n>       timer.verify_duration(3)  # Fail if login takes more than 3 seconds\n\ntest_login_all_users.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <OOP.timer.Timer object at 0x104fef950>, max_seconds = 3\n\n    def verify_duration(self, max_seconds):\n        duration = self.get_duration()\n>       assert duration <= max_seconds, f\"Operation took too long: {duration:.2f} seconds (maximum allowed: {max_seconds} seconds)\"\nE       AssertionError: Operation took too long: 5.15 seconds (maximum allowed: 3 seconds)\n\nOOP/timer.py:28: AssertionError"}, "parameters": [{"name": "username", "value": "'performance_glitch_user'"}], "start": 1734735435761, "stop": 1734735441352, "uuid": "b168525c-358c-4633-b027-4b6c649eab87", "historyId": "abd60bb8c370d1d13ef2bbdca9f3305f", "testCaseId": "fdf410d01c62b6176f96ce0a24802f93", "fullName": "test_login_all_users.TestLogin#test_login_all_users", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('driver')"}, {"name": "suite", "value": "test_login_all_users"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "192.168.68.133"}, {"name": "thread", "value": "19913-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_all_users"}]}